[package]
name = "once-list"
version = "0.1.0"
edition = "2021"

[dependencies]
allocator-api2 = { path = "../allocator-api2" }

[features]
default = []
nightly = ["allocator-api2/nightly"]
sync = []
